[0m17:01:22.899633 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbf9ef20b30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbf9f602f90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbf9f601250>]}


============================== 17:01:22.903883 | cd584bc3-7274-41b8-b1f0-f318fd299eda ==============================
[0m17:01:22.903883 [info ] [MainThread]: Running with dbt=1.9.3
[0m17:01:22.904977 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/home/sanjana/airflow/dags/my_dbt_project', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run --profiles-dir /home/sanjana/airflow/dags/my_dbt_project', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:01:22.906100 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/sanjana/airflow/dags/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:01:22.911651 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.1198005, "process_in_blocks": "0", "process_kernel_time": 0.131819, "process_mem_max_rss": "98608", "process_out_blocks": "8", "process_user_time": 2.038136}
[0m17:01:22.912316 [debug] [MainThread]: Command `dbt run` failed at 17:01:22.912159 after 0.12 seconds
[0m17:01:22.912929 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbfa2ba7170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbf9ec411c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbf9ec41e80>]}
[0m17:01:22.913578 [debug] [MainThread]: Flushing usage events
[0m17:01:23.738441 [debug] [MainThread]: An error was encountered while trying to flush usage events
